sudo: required
services:
  - docker

before_install:
  - docker build -t jarrmill/build-test -f ./Dockerfile ./

script:
  - docker run jarrmill/build-test npm test -- --coverage

after_success:
  - docker build -t jarrmill/commit-spy ./
  - docker build -t jarrmill/commit-spy-nginx ./nginx/
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jarrmill/commit-spy
  - docker push jarrmill/commit-spy-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: commit-spy
  env: CommitSpy-env
  bucket_name: elasticbeanstalk-us-east-1-531609046656
  bucket_path: commit-spy
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


