sudo: required
services:
  - docker

before_install:
  - docker build -t jarrmill/build-test -f ./Dockerfile ./

script:
  - docker run jarrmill/build-test npm test -- --coverage

after_success:
  - docker build -t jarrmill/commit-spy ./
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jarrmill/commit-spy


