version: '3'
services:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  postgres:
    image: 'postgres:latest'
  nginx:
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3001:80'
      - '443:443'
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - /.:/app
  

