version: '3'
services:
  postgres:
    image: 'postgres:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3001:80'
      - '443:443'
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - /.:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - TEST_VAR='SUCCESS'
  

