version: '3'
services:
  postgres:
    image: 'postgres:latest'
  router:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - /.:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - TEST_VAR='SUCCESS'
  

